name: "Active Directory authentication Add-on"
version: "2.1.0"
slug: "ldapauth"
description: "Active Directory authentication add-on for HAOS with LDAP and LDAPS support"
url: https://github.com/napalmyourmom/home-assistant-active-directory-auth
init: false
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
host_network: true
log:
  max_size: 1m
  max_files: 1
map:
  - ssl:ro
  - share:rw
  - config:ro
schema:
  ldap_server: str
  bind_user: str
  bind_password: password
  user_base_dn: str
  groups_base_dn: str
  user_group: str
  admin_group: str
  enable_ldaps: bool?
  ldaps_verify: bool?
  ldaps_ca_pem: str?
  debug_logging: bool?
